#!/bin/sh

FOCUS_REPO="$HOME/.ifocustt"
FOCUS_PREFIX="/usr/local"
FOCUS_COMMAND="focus"
INSTALLATION_LOCATION="$FOCUS_PREFIX/bin/$FOCUS_COMMAND"

set -e

if [ ! -d "$FOCUS_REPO" ]
then
  git clone https://github.com/binarymason/ifocustt.git "$FOCUS_REPO"
  {
    cd "$FOCUS_REPO"
    bundle install --deployment
  }
fi

if [ ! -L  "$INSTALLATION_LOCATION" ]
then
  ln -s "$FOCUS_REPO/bin/$FOCUS_COMMAND" "$INSTALLATION_LOCATION"
fi

echo "Focus successfully installed!"
